build aws cloudformation image:
  extends: .build
  stage: build
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/aws-cloudformation:$CI_COMMIT_SHA"
  script:
    - docker build -t "$BUILD_IMAGE_NAME" -f "aws/cloudformation/Dockerfile" --build-arg BASE_VERSION="$CI_COMMIT_SHA" .

test aws cloudformation command:
  extends: .test-command
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/aws-cloudformation:$CI_COMMIT_SHA"
  script:
    - jq --version
    - bc --version
    - aws cloudformation help

publish aws cloudformation:
  extends: .publish-tag
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/aws-cloudformation:$CI_COMMIT_SHA"
    IMAGE_NAME_FOR_REGISTRY: "$CI_REGISTRY_IMAGE/aws-cloudformation"

