#!/bin/bash

set -eo pipefail

TARGET_PATH=${CI_REGISTRY}/${CI_PROJET_PATH}/${TARGET_IMAGE_NAME}

registry_credentials_available() {
    echo "-> Checking registry credentials"
    [[ -n "${CI_REGISTRY_USER}" ]] && [[ -n "${CI_REGISTRY_PASSWORD}" ]] && return 0
    return 1
}

login() {
    echo "-> Logging into registry"
    registry_credentials_available || return 0
    docker login --username ${CI_REGISTRY_USER} --password ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
}

logout() {
    echo "-> Logging out of registry"
    docker logout ${CI_REGISTRY}
}

pull () {
    echo "-> Pulling image"
    registry_credentials_available || return 0
    docker pull ${TARGET_PATH} || echo "${TARGET_PATH} image is not available. Will not use cache."
}

push () {
    registry_credentials_available || return 0
    if [[ -z "${PUSH_TO_REGISTRY}" ]] || [[ "${PUSH_TO_REGISTRY}" != "true" ]]; then
      echo "-> Skipping push to registry"
      return 0
    else
      echo "-> Pushing image"
      docker push ${TARGET_PATH}
    fi
}


build() {
    echo "-> Building image: ${TARGET_IMAGE}"
    docker build \
           --cache-from ${TARGET_IMAGE} \
           -t ${TARGET_IMAGE} \
           -f ${TARGET_DOCKERFILE} \
           .
}

login
pull
build
push
logout
