build cloud deploy image:
  extends: .build
  stage: build
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  script:
    - docker build -t "$BUILD_IMAGE_NAME" -f "aws/cloud_deploy/Dockerfile" .

test aws commands for cloud deploy:
  extends: .test-command
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
  script: 
    - aws --version
    - aws ecs help
    - groff --version
    - jq --version
    - bc --version

release cloud deploy:
  extends: .release-tag
  variables:
    BUILD_IMAGE_NAME: "$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG:$CI_COMMIT_SHA"
    IMAGE_NAME_FOR_REGISTRY: "$CI_REGISTRY_IMAGE"

